# Generated by Django 4.1.5 on 2023-01-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='edges',
        ),
        migrations.AddField(
            model_name='node',
            name='child_nodes',
            field=models.ManyToManyField(blank=True, related_name='parent_nodes', through='core.Edge', to='core.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='core.node'),
        ),
    ]
