# Generated by Django 4.1.5 on 2023-01-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_node_edges_node_child_nodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='core.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='core.node'),
        ),
    ]
